#line 2 "cs_test%LoadConfig_test0%cs_error"
/* LoadConfig_test0.c */
#ifndef __LoadConfig_test0__
#define __LoadConfig_test0__

#include "../factory/factory.h"

#include "LoadConfig_test0.h"

void CS_TEST LoadConfig_test0()
{
	/*Do not modify CS_TEST_PARAMETER()*/
	CS_TEST_PARAMETER(LoadConfig_test0);
	/*Do not remove connect_stub_configuration()*/
	int cs_stub_connect_function_call = connect_LoadConfig_test0_stub_configuration();
	{/*<START TEST>*/

#line 1 "cs_test%LoadConfig_test0%User code start"
static struct g_i2cTransfer
{
    uint32  mode;
    uint32  length;
    uint8   * data;
} g_i2cTransfer_t;

static volatile struct g_sciTransfer
{
    uint32   mode;         /* Used to check for TX interrupt Enable */  
    uint32   tx_length;    /* Transmit data length in number of Bytes */
	uint32   rx_length;    /* Receive data length in number of Bytes */  
    uint8    * tx_data;    /* Transmit data pointer */  	
    uint8    * rx_data;    /* Receive data pointer */  
} g_sciTransfer_t[2U];
static uint32 s_het1pwmPolarity[8U] =
{
    3U,
    1U,
    3U,
    3U,
    3U,
    1U,
    3U,
    3U,
};

static uint32 s_het2pwmPolarity[8U] =
{
    3U,
    3U,
    3U,
    3U,
    3U,
    3U,
    3U,
    3U,
};
#line 58 "cs_test%LoadConfig_test0%cs_error"
	/*Declaration (parameter/return/target object) variables*/
	struct _SigPI_t confLogic_PI0_pSigPI_mem [1]={0,}; 
	struct _SigDI_t confLogic_DI0_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic0_DI0_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic0_DI1_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic0_DI2_pSigDI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic0_PI0_pSigPI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic0_PI1_pSigPI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic1_PI0_pSigPI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic1_PI1_pSigPI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic1_DI0_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic1_DI1_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic1_DI2_pSigDI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic2_PI0_pSigPI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic2_PI1_pSigPI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic2_DI0_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic2_DI1_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic2_DI2_pSigDI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic3_PI0_pSigPI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic3_PI1_pSigPI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic3_DI0_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic3_DI1_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic3_DI2_pSigDI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic4_PI0_pSigPI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic4_PI1_pSigPI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic4_DI0_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic4_DI1_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic4_DI2_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic5_DI0_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic5_DI1_pSigDI_mem [1]={0,}; 
	struct _SigDI_t g_ConfLogic5_DI2_pSigDI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic5_PI0_pSigPI_mem [1]={0,}; 
	struct _SigPI_t g_ConfLogic5_PI1_pSigPI_mem [1]={0,}; 
	unsigned char g_sciTransfer_t0_tx_data_mem [1]={0,}; 
	unsigned char g_sciTransfer_t0_rx_data_mem [1]={0,}; 
	struct i2cBase i2cREG1_tmp_mem [1]={0,}; 

	/*Memory assign*/
	confLogic.PI[0].pSigPI = confLogic_PI0_pSigPI_mem;
	confLogic.DI[0].pSigDI = confLogic_DI0_pSigDI_mem;
	g_ConfLogic[0].DI[0].pSigDI = g_ConfLogic0_DI0_pSigDI_mem;
	g_ConfLogic[0].DI[1].pSigDI = g_ConfLogic0_DI1_pSigDI_mem;
	g_ConfLogic[0].DI[2].pSigDI = g_ConfLogic0_DI2_pSigDI_mem;
	g_ConfLogic[0].PI[0].pSigPI = g_ConfLogic0_PI0_pSigPI_mem;
	g_ConfLogic[0].PI[1].pSigPI = g_ConfLogic0_PI1_pSigPI_mem;
	g_ConfLogic[1].PI[0].pSigPI = g_ConfLogic1_PI0_pSigPI_mem;
	g_ConfLogic[1].PI[1].pSigPI = g_ConfLogic1_PI1_pSigPI_mem;
	g_ConfLogic[1].DI[0].pSigDI = g_ConfLogic1_DI0_pSigDI_mem;
	g_ConfLogic[1].DI[1].pSigDI = g_ConfLogic1_DI1_pSigDI_mem;
	g_ConfLogic[1].DI[2].pSigDI = g_ConfLogic1_DI2_pSigDI_mem;
	g_ConfLogic[2].PI[0].pSigPI = g_ConfLogic2_PI0_pSigPI_mem;
	g_ConfLogic[2].PI[1].pSigPI = g_ConfLogic2_PI1_pSigPI_mem;
	g_ConfLogic[2].DI[0].pSigDI = g_ConfLogic2_DI0_pSigDI_mem;
	g_ConfLogic[2].DI[1].pSigDI = g_ConfLogic2_DI1_pSigDI_mem;
	g_ConfLogic[2].DI[2].pSigDI = g_ConfLogic2_DI2_pSigDI_mem;
	g_ConfLogic[3].PI[0].pSigPI = g_ConfLogic3_PI0_pSigPI_mem;
	g_ConfLogic[3].PI[1].pSigPI = g_ConfLogic3_PI1_pSigPI_mem;
	g_ConfLogic[3].DI[0].pSigDI = g_ConfLogic3_DI0_pSigDI_mem;
	g_ConfLogic[3].DI[1].pSigDI = g_ConfLogic3_DI1_pSigDI_mem;
	g_ConfLogic[3].DI[2].pSigDI = g_ConfLogic3_DI2_pSigDI_mem;
	g_ConfLogic[4].PI[0].pSigPI = g_ConfLogic4_PI0_pSigPI_mem;
	g_ConfLogic[4].PI[1].pSigPI = g_ConfLogic4_PI1_pSigPI_mem;
	g_ConfLogic[4].DI[0].pSigDI = g_ConfLogic4_DI0_pSigDI_mem;
	g_ConfLogic[4].DI[1].pSigDI = g_ConfLogic4_DI1_pSigDI_mem;
	g_ConfLogic[4].DI[2].pSigDI = g_ConfLogic4_DI2_pSigDI_mem;
	g_ConfLogic[5].DI[0].pSigDI = g_ConfLogic5_DI0_pSigDI_mem;
	g_ConfLogic[5].DI[1].pSigDI = g_ConfLogic5_DI1_pSigDI_mem;
	g_ConfLogic[5].DI[2].pSigDI = g_ConfLogic5_DI2_pSigDI_mem;
	g_ConfLogic[5].PI[0].pSigPI = g_ConfLogic5_PI0_pSigPI_mem;
	g_ConfLogic[5].PI[1].pSigPI = g_ConfLogic5_PI1_pSigPI_mem;
	g_sciTransfer_t[0].tx_data = g_sciTransfer_t0_tx_data_mem;
	g_sciTransfer_t[0].rx_data = g_sciTransfer_t0_rx_data_mem;
	i2cREG1_tmp = i2cREG1_tmp_mem;

	/*Input*/
	confLogic.opGate[0].Gate = CS_UINT_INPUT(unsigned char,"confLogic.opGate[0].Gate");
	confLogic.opGate[1].Gate = CS_UINT_INPUT(unsigned char,"confLogic.opGate[1].Gate");
	confLogic.opGate[2].Gate = CS_UINT_INPUT(unsigned char,"confLogic.opGate[2].Gate");
	confLogic.opGate[3].Gate = CS_UINT_INPUT(unsigned char,"confLogic.opGate[3].Gate");
	confLogic.opGate[4].Gate = CS_UINT_INPUT(unsigned char,"confLogic.opGate[4].Gate");
	confLogic.opGate[5].Gate = CS_UINT_INPUT(unsigned char,"confLogic.opGate[5].Gate");
	confLogic.opGate[6].Gate = CS_UINT_INPUT(unsigned char,"confLogic.opGate[6].Gate");
	confLogic.opGate[7].Gate = CS_UINT_INPUT(unsigned char,"confLogic.opGate[7].Gate");
	confLogic.cntDI = CS_INT_INPUT(int,"confLogic.cntDI");
	confLogic.cntOpGate = CS_INT_INPUT(int,"confLogic.cntOpGate");
	confLogic.cntPI = CS_INT_INPUT(int,"confLogic.cntPI");
	g_ConfLogic0_DI0_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic0_DI0_pSigDI_mem[0].nValue");
	g_ConfLogic0_DI0_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic0_DI0_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[0].DI[0].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[0].nDType");
	g_ConfLogic[0].DI[0].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[0].bInvert");
	g_ConfLogic[0].DI[0].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[0].DI[0].nDTime");
	g_ConfLogic[0].DI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[0].DI[0].nNum");
	g_ConfLogic[0].DI[0].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[0].DI[0].nUpdateTime");
	g_ConfLogic[0].DI[0].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[0].nDIVal");
	g_ConfLogic[0].DI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[0].nValue");
	g_ConfLogic[0].DI[1].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[0].DI[1].nDTime");
	g_ConfLogic0_DI1_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic0_DI1_pSigDI_mem[0].nRemainTime");
	g_ConfLogic0_DI1_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic0_DI1_pSigDI_mem[0].nValue");
	g_ConfLogic[0].DI[1].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[1].nDIVal");
	g_ConfLogic[0].DI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[0].DI[1].nNum");
	g_ConfLogic[0].DI[1].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[1].nDType");
	g_ConfLogic[0].DI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[1].nValue");
	g_ConfLogic[0].DI[1].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[0].DI[1].nUpdateTime");
	g_ConfLogic[0].DI[1].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[1].bInvert");
	g_ConfLogic[0].DI[2].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[0].DI[2].nDTime");
	g_ConfLogic[0].DI[2].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[2].nDType");
	g_ConfLogic[0].DI[2].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[2].nValue");
	g_ConfLogic[0].DI[2].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[0].DI[2].nUpdateTime");
	g_ConfLogic[0].DI[2].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[2].bInvert");
	g_ConfLogic[0].DI[2].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DI[2].nDIVal");
	g_ConfLogic0_DI2_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic0_DI2_pSigDI_mem[0].nValue");
	g_ConfLogic0_DI2_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic0_DI2_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[0].DI[2].nNum = CS_INT_INPUT(int,"g_ConfLogic[0].DI[2].nNum");
	g_ConfLogic[0].DO._nOldCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DO._nOldCalcVal");
	g_ConfLogic[0].DO.nActiveLevel = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DO.nActiveLevel");
	g_ConfLogic[0].DO.nNum = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DO.nNum");
	g_ConfLogic[0].DO._nPulseTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[0].DO._nPulseTime");
	g_ConfLogic[0].DO.nCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DO.nCalcVal");
	g_ConfLogic[0].DO.nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DO.nValue");
	g_ConfLogic[0].DO._DOSt = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DO._DOSt");
	g_ConfLogic[0].DO.nPeriod = CS_UINT_INPUT(unsigned short,"g_ConfLogic[0].DO.nPeriod");
	g_ConfLogic[0].DO.nOutputType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DO.nOutputType");
	g_ConfLogic[0].DO.nDutyRatio = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].DO.nDutyRatio");
	g_ConfLogic[0].cntOpGate = CS_INT_INPUT(int,"g_ConfLogic[0].cntOpGate");
	g_ConfLogic[0].cntPI = CS_INT_INPUT(int,"g_ConfLogic[0].cntPI");
	g_ConfLogic[0].opGate[0].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].opGate[0].Gate");
	g_ConfLogic[0].opGate[1].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].opGate[1].Gate");
	g_ConfLogic[0].PI[0].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].PI[0].nSpare3[0]");
	g_ConfLogic[0].PI[0].nSpare3[1] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].PI[0].nSpare3[1]");
	g_ConfLogic[0].PI[0].nSpare3[2] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].PI[0].nSpare3[2]");
	g_ConfLogic[0].PI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[0].PI[0].nNum");
	g_ConfLogic0_PI0_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic0_PI0_pSigPI_mem[0].nFreqency");
	g_ConfLogic[0].PI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].PI[0].nValue");
	g_ConfLogic[0].PI[0].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].PI[0].nComp");
	g_ConfLogic[0].PI[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[0].PI[0].nFreqency");
	g_ConfLogic[0].PI[1].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].PI[1].nSpare3[0]");
	g_ConfLogic0_PI1_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic0_PI1_pSigPI_mem[0].nFreqency");
	g_ConfLogic[0].PI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[0].PI[1].nNum");
	g_ConfLogic[0].PI[1].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[0].PI[1].nFreqency");
	g_ConfLogic[0].PI[1].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].PI[1].nComp");
	g_ConfLogic[0].PI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[0].PI[1].nValue");
	g_ConfLogic[0].cntDI = CS_INT_INPUT(int,"g_ConfLogic[0].cntDI");
	g_ConfLogic[1].cntDI = CS_INT_INPUT(int,"g_ConfLogic[1].cntDI");
	g_ConfLogic[1].opGate[0].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].opGate[0].Gate");
	g_ConfLogic[1].opGate[1].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].opGate[1].Gate");
	g_ConfLogic[1].cntOpGate = CS_INT_INPUT(int,"g_ConfLogic[1].cntOpGate");
	g_ConfLogic[1].DO.nOutputType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DO.nOutputType");
	g_ConfLogic[1].DO.nActiveLevel = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DO.nActiveLevel");
	g_ConfLogic[1].DO._nOldCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DO._nOldCalcVal");
	g_ConfLogic[1].DO._DOSt = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DO._DOSt");
	g_ConfLogic[1].DO._nPulseTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[1].DO._nPulseTime");
	g_ConfLogic[1].DO.nPeriod = CS_UINT_INPUT(unsigned short,"g_ConfLogic[1].DO.nPeriod");
	g_ConfLogic[1].DO.nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DO.nValue");
	g_ConfLogic[1].DO.nCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DO.nCalcVal");
	g_ConfLogic[1].DO.nNum = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DO.nNum");
	g_ConfLogic[1].DO.nDutyRatio = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DO.nDutyRatio");
	g_ConfLogic[1].PI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].PI[0].nValue");
	g_ConfLogic[1].PI[0].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].PI[0].nComp");
	g_ConfLogic[1].PI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[1].PI[0].nNum");
	g_ConfLogic[1].PI[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[1].PI[0].nFreqency");
	g_ConfLogic[1].PI[0].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].PI[0].nSpare3[0]");
	g_ConfLogic[1].PI[0].nSpare3[1] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].PI[0].nSpare3[1]");
	g_ConfLogic[1].PI[0].nSpare3[2] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].PI[0].nSpare3[2]");
	g_ConfLogic1_PI0_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic1_PI0_pSigPI_mem[0].nFreqency");
	g_ConfLogic[1].PI[1].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].PI[1].nSpare3[0]");
	g_ConfLogic[1].PI[1].nSpare3[1] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].PI[1].nSpare3[1]");
	g_ConfLogic[1].PI[1].nSpare3[2] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].PI[1].nSpare3[2]");
	g_ConfLogic[1].PI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].PI[1].nValue");
	g_ConfLogic1_PI1_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic1_PI1_pSigPI_mem[0].nFreqency");
	g_ConfLogic[1].PI[1].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].PI[1].nComp");
	g_ConfLogic[1].PI[1].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[1].PI[1].nFreqency");
	g_ConfLogic[1].PI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[1].PI[1].nNum");
	g_ConfLogic[1].cntPI = CS_INT_INPUT(int,"g_ConfLogic[1].cntPI");
	g_ConfLogic[1].DI[0].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[0].nDType");
	g_ConfLogic[1].DI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[0].nValue");
	g_ConfLogic[1].DI[0].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[0].bInvert");
	g_ConfLogic[1].DI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[1].DI[0].nNum");
	g_ConfLogic1_DI0_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic1_DI0_pSigDI_mem[0].nValue");
	g_ConfLogic1_DI0_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic1_DI0_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[1].DI[0].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[0].nDIVal");
	g_ConfLogic[1].DI[0].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[1].DI[0].nUpdateTime");
	g_ConfLogic[1].DI[0].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[1].DI[0].nDTime");
	g_ConfLogic1_DI1_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic1_DI1_pSigDI_mem[0].nValue");
	g_ConfLogic1_DI1_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic1_DI1_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[1].DI[1].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[1].nDIVal");
	g_ConfLogic[1].DI[1].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[1].bInvert");
	g_ConfLogic[1].DI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[1].DI[1].nNum");
	g_ConfLogic[1].DI[1].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[1].nDType");
	g_ConfLogic[1].DI[1].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[1].DI[1].nDTime");
	g_ConfLogic[1].DI[1].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[1].DI[1].nUpdateTime");
	g_ConfLogic[1].DI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[1].nValue");
	g_ConfLogic1_DI2_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic1_DI2_pSigDI_mem[0].nRemainTime");
	g_ConfLogic1_DI2_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic1_DI2_pSigDI_mem[0].nValue");
	g_ConfLogic[1].DI[2].nNum = CS_INT_INPUT(int,"g_ConfLogic[1].DI[2].nNum");
	g_ConfLogic[1].DI[2].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[2].nDIVal");
	g_ConfLogic[1].DI[2].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[1].DI[2].nUpdateTime");
	g_ConfLogic[1].DI[2].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[2].nValue");
	g_ConfLogic[1].DI[2].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[1].DI[2].nDTime");
	g_ConfLogic[1].DI[2].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[2].bInvert");
	g_ConfLogic[1].DI[2].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[1].DI[2].nDType");
	g_ConfLogic[2].cntPI = CS_INT_INPUT(int,"g_ConfLogic[2].cntPI");
	g_ConfLogic[2].cntOpGate = CS_INT_INPUT(int,"g_ConfLogic[2].cntOpGate");
	g_ConfLogic[2].DO.nPeriod = CS_UINT_INPUT(unsigned short,"g_ConfLogic[2].DO.nPeriod");
	g_ConfLogic[2].DO._DOSt = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DO._DOSt");
	g_ConfLogic[2].DO.nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DO.nValue");
	g_ConfLogic[2].DO.nNum = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DO.nNum");
	g_ConfLogic[2].DO.nCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DO.nCalcVal");
	g_ConfLogic[2].DO.nOutputType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DO.nOutputType");
	g_ConfLogic[2].DO._nOldCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DO._nOldCalcVal");
	g_ConfLogic[2].DO.nActiveLevel = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DO.nActiveLevel");
	g_ConfLogic[2].DO.nDutyRatio = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DO.nDutyRatio");
	g_ConfLogic[2].DO._nPulseTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[2].DO._nPulseTime");
	g_ConfLogic2_PI0_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic2_PI0_pSigPI_mem[0].nFreqency");
	g_ConfLogic[2].PI[0].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].PI[0].nComp");
	g_ConfLogic[2].PI[0].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].PI[0].nSpare3[0]");
	g_ConfLogic[2].PI[0].nSpare3[1] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].PI[0].nSpare3[1]");
	g_ConfLogic[2].PI[0].nSpare3[2] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].PI[0].nSpare3[2]");
	g_ConfLogic[2].PI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[2].PI[0].nNum");
	g_ConfLogic[2].PI[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[2].PI[0].nFreqency");
	g_ConfLogic[2].PI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].PI[0].nValue");
	g_ConfLogic[2].PI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].PI[1].nValue");
	g_ConfLogic2_PI1_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic2_PI1_pSigPI_mem[0].nFreqency");
	g_ConfLogic[2].PI[1].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[2].PI[1].nFreqency");
	g_ConfLogic[2].PI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[2].PI[1].nNum");
	g_ConfLogic[2].PI[1].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].PI[1].nComp");
	g_ConfLogic[2].PI[1].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].PI[1].nSpare3[0]");
	g_ConfLogic[2].PI[1].nSpare3[1] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].PI[1].nSpare3[1]");
	g_ConfLogic[2].PI[1].nSpare3[2] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].PI[1].nSpare3[2]");
	g_ConfLogic[2].DI[0].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[2].DI[0].nUpdateTime");
	g_ConfLogic[2].DI[0].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[2].DI[0].nDTime");
	g_ConfLogic[2].DI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[2].DI[0].nNum");
	g_ConfLogic[2].DI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[0].nValue");
	g_ConfLogic[2].DI[0].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[0].bInvert");
	g_ConfLogic2_DI0_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic2_DI0_pSigDI_mem[0].nRemainTime");
	g_ConfLogic2_DI0_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic2_DI0_pSigDI_mem[0].nValue");
	g_ConfLogic[2].DI[0].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[0].nDIVal");
	g_ConfLogic[2].DI[0].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[0].nDType");
	g_ConfLogic[2].DI[1].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[2].DI[1].nUpdateTime");
	g_ConfLogic[2].DI[1].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[2].DI[1].nDTime");
	g_ConfLogic[2].DI[1].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[1].bInvert");
	g_ConfLogic[2].DI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[1].nValue");
	g_ConfLogic[2].DI[1].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[1].nDType");
	g_ConfLogic2_DI1_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic2_DI1_pSigDI_mem[0].nValue");
	g_ConfLogic2_DI1_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic2_DI1_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[2].DI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[2].DI[1].nNum");
	g_ConfLogic[2].DI[1].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[1].nDIVal");
	g_ConfLogic[2].DI[2].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[2].nDType");
	g_ConfLogic[2].DI[2].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[2].nDIVal");
	g_ConfLogic[2].DI[2].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[2].nValue");
	g_ConfLogic[2].DI[2].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].DI[2].bInvert");
	g_ConfLogic[2].DI[2].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[2].DI[2].nDTime");
	g_ConfLogic[2].DI[2].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[2].DI[2].nUpdateTime");
	g_ConfLogic2_DI2_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic2_DI2_pSigDI_mem[0].nValue");
	g_ConfLogic2_DI2_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic2_DI2_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[2].DI[2].nNum = CS_INT_INPUT(int,"g_ConfLogic[2].DI[2].nNum");
	g_ConfLogic[2].cntDI = CS_INT_INPUT(int,"g_ConfLogic[2].cntDI");
	g_ConfLogic[2].opGate[0].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].opGate[0].Gate");
	g_ConfLogic[2].opGate[1].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[2].opGate[1].Gate");
	g_ConfLogic[3].cntPI = CS_INT_INPUT(int,"g_ConfLogic[3].cntPI");
	g_ConfLogic[3].PI[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[3].PI[0].nFreqency");
	g_ConfLogic[3].PI[0].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].PI[0].nComp");
	g_ConfLogic[3].PI[0].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].PI[0].nSpare3[0]");
	g_ConfLogic[3].PI[0].nSpare3[1] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].PI[0].nSpare3[1]");
	g_ConfLogic[3].PI[0].nSpare3[2] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].PI[0].nSpare3[2]");
	g_ConfLogic[3].PI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[3].PI[0].nNum");
	g_ConfLogic3_PI0_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic3_PI0_pSigPI_mem[0].nFreqency");
	g_ConfLogic[3].PI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].PI[0].nValue");
	g_ConfLogic[3].PI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[3].PI[1].nNum");
	g_ConfLogic[3].PI[1].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[3].PI[1].nFreqency");
	g_ConfLogic[3].PI[1].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].PI[1].nComp");
	g_ConfLogic[3].PI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].PI[1].nValue");
	g_ConfLogic3_PI1_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic3_PI1_pSigPI_mem[0].nFreqency");
	g_ConfLogic[3].PI[1].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].PI[1].nSpare3[0]");
	g_ConfLogic[3].PI[1].nSpare3[1] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].PI[1].nSpare3[1]");
	g_ConfLogic[3].PI[1].nSpare3[2] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].PI[1].nSpare3[2]");
	g_ConfLogic[3].opGate[0].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].opGate[0].Gate");
	g_ConfLogic[3].opGate[1].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].opGate[1].Gate");
	g_ConfLogic[3].DO._nPulseTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[3].DO._nPulseTime");
	g_ConfLogic[3].DO._DOSt = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DO._DOSt");
	g_ConfLogic[3].DO.nActiveLevel = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DO.nActiveLevel");
	g_ConfLogic[3].DO.nDutyRatio = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DO.nDutyRatio");
	g_ConfLogic[3].DO._nOldCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DO._nOldCalcVal");
	g_ConfLogic[3].DO.nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DO.nValue");
	g_ConfLogic[3].DO.nOutputType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DO.nOutputType");
	g_ConfLogic[3].DO.nPeriod = CS_UINT_INPUT(unsigned short,"g_ConfLogic[3].DO.nPeriod");
	g_ConfLogic[3].DO.nNum = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DO.nNum");
	g_ConfLogic[3].DO.nCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DO.nCalcVal");
	g_ConfLogic[3].cntOpGate = CS_INT_INPUT(int,"g_ConfLogic[3].cntOpGate");
	g_ConfLogic[3].cntDI = CS_INT_INPUT(int,"g_ConfLogic[3].cntDI");
	g_ConfLogic3_DI0_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic3_DI0_pSigDI_mem[0].nValue");
	g_ConfLogic3_DI0_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic3_DI0_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[3].DI[0].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[0].nDIVal");
	g_ConfLogic[3].DI[0].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[3].DI[0].nDTime");
	g_ConfLogic[3].DI[0].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[0].bInvert");
	g_ConfLogic[3].DI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[0].nValue");
	g_ConfLogic[3].DI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[3].DI[0].nNum");
	g_ConfLogic[3].DI[0].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[3].DI[0].nUpdateTime");
	g_ConfLogic[3].DI[0].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[0].nDType");
	g_ConfLogic[3].DI[1].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[3].DI[1].nUpdateTime");
	g_ConfLogic[3].DI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[3].DI[1].nNum");
	g_ConfLogic[3].DI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[1].nValue");
	g_ConfLogic[3].DI[1].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[1].nDType");
	g_ConfLogic[3].DI[1].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[1].nDIVal");
	g_ConfLogic[3].DI[1].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[1].bInvert");
	g_ConfLogic[3].DI[1].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[3].DI[1].nDTime");
	g_ConfLogic3_DI1_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic3_DI1_pSigDI_mem[0].nRemainTime");
	g_ConfLogic3_DI1_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic3_DI1_pSigDI_mem[0].nValue");
	g_ConfLogic[3].DI[2].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[3].DI[2].nUpdateTime");
	g_ConfLogic[3].DI[2].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[2].bInvert");
	g_ConfLogic[3].DI[2].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[3].DI[2].nDTime");
	g_ConfLogic[3].DI[2].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[2].nDType");
	g_ConfLogic3_DI2_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic3_DI2_pSigDI_mem[0].nRemainTime");
	g_ConfLogic3_DI2_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic3_DI2_pSigDI_mem[0].nValue");
	g_ConfLogic[3].DI[2].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[2].nDIVal");
	g_ConfLogic[3].DI[2].nNum = CS_INT_INPUT(int,"g_ConfLogic[3].DI[2].nNum");
	g_ConfLogic[3].DI[2].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[3].DI[2].nValue");
	g_ConfLogic[4].DO.nActiveLevel = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DO.nActiveLevel");
	g_ConfLogic[4].DO.nNum = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DO.nNum");
	g_ConfLogic[4].DO._nPulseTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[4].DO._nPulseTime");
	g_ConfLogic[4].DO.nDutyRatio = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DO.nDutyRatio");
	g_ConfLogic[4].DO.nCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DO.nCalcVal");
	g_ConfLogic[4].DO.nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DO.nValue");
	g_ConfLogic[4].DO.nOutputType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DO.nOutputType");
	g_ConfLogic[4].DO._DOSt = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DO._DOSt");
	g_ConfLogic[4].DO.nPeriod = CS_UINT_INPUT(unsigned short,"g_ConfLogic[4].DO.nPeriod");
	g_ConfLogic[4].DO._nOldCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DO._nOldCalcVal");
	g_ConfLogic[4].PI[0].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].PI[0].nComp");
	g_ConfLogic[4].PI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].PI[0].nValue");
	g_ConfLogic[4].PI[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[4].PI[0].nFreqency");
	g_ConfLogic[4].PI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[4].PI[0].nNum");
	g_ConfLogic4_PI0_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic4_PI0_pSigPI_mem[0].nFreqency");
	g_ConfLogic[4].PI[0].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].PI[0].nSpare3[0]");
	g_ConfLogic[4].PI[0].nSpare3[1] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].PI[0].nSpare3[1]");
	g_ConfLogic[4].PI[0].nSpare3[2] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].PI[0].nSpare3[2]");
	g_ConfLogic[4].PI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[4].PI[1].nNum");
	g_ConfLogic[4].PI[1].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[4].PI[1].nFreqency");
	g_ConfLogic4_PI1_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic4_PI1_pSigPI_mem[0].nFreqency");
	g_ConfLogic[4].PI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].PI[1].nValue");
	g_ConfLogic[4].PI[1].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].PI[1].nComp");
	g_ConfLogic[4].PI[1].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].PI[1].nSpare3[0]");
	g_ConfLogic[4].PI[1].nSpare3[1] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].PI[1].nSpare3[1]");
	g_ConfLogic[4].PI[1].nSpare3[2] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].PI[1].nSpare3[2]");
	g_ConfLogic[4].cntPI = CS_INT_INPUT(int,"g_ConfLogic[4].cntPI");
	g_ConfLogic[4].cntOpGate = CS_INT_INPUT(int,"g_ConfLogic[4].cntOpGate");
	g_ConfLogic[4].opGate[0].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].opGate[0].Gate");
	g_ConfLogic[4].opGate[1].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].opGate[1].Gate");
	g_ConfLogic[4].DI[0].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[0].nDType");
	g_ConfLogic[4].DI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[0].nValue");
	g_ConfLogic[4].DI[0].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[4].DI[0].nDTime");
	g_ConfLogic[4].DI[0].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[0].bInvert");
	g_ConfLogic4_DI0_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic4_DI0_pSigDI_mem[0].nValue");
	g_ConfLogic4_DI0_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic4_DI0_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[4].DI[0].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[0].nDIVal");
	g_ConfLogic[4].DI[0].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[4].DI[0].nUpdateTime");
	g_ConfLogic[4].DI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[4].DI[0].nNum");
	g_ConfLogic4_DI1_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic4_DI1_pSigDI_mem[0].nValue");
	g_ConfLogic4_DI1_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic4_DI1_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[4].DI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[1].nValue");
	g_ConfLogic[4].DI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[4].DI[1].nNum");
	g_ConfLogic[4].DI[1].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[1].nDIVal");
	g_ConfLogic[4].DI[1].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[1].bInvert");
	g_ConfLogic[4].DI[1].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[4].DI[1].nDTime");
	g_ConfLogic[4].DI[1].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[4].DI[1].nUpdateTime");
	g_ConfLogic[4].DI[1].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[1].nDType");
	g_ConfLogic[4].DI[2].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[4].DI[2].nUpdateTime");
	g_ConfLogic[4].DI[2].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[2].nDType");
	g_ConfLogic[4].DI[2].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[2].nValue");
	g_ConfLogic4_DI2_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic4_DI2_pSigDI_mem[0].nValue");
	g_ConfLogic4_DI2_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic4_DI2_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[4].DI[2].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[2].nDIVal");
	g_ConfLogic[4].DI[2].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[4].DI[2].bInvert");
	g_ConfLogic[4].DI[2].nNum = CS_INT_INPUT(int,"g_ConfLogic[4].DI[2].nNum");
	g_ConfLogic[4].DI[2].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[4].DI[2].nDTime");
	g_ConfLogic[4].cntDI = CS_INT_INPUT(int,"g_ConfLogic[4].cntDI");
	g_ConfLogic[5].DI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[5].DI[0].nNum");
	g_ConfLogic[5].DI[0].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[0].bInvert");
	g_ConfLogic[5].DI[0].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[0].nDType");
	g_ConfLogic[5].DI[0].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[5].DI[0].nUpdateTime");
	g_ConfLogic5_DI0_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic5_DI0_pSigDI_mem[0].nValue");
	g_ConfLogic5_DI0_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic5_DI0_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[5].DI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[0].nValue");
	g_ConfLogic[5].DI[0].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[5].DI[0].nDTime");
	g_ConfLogic[5].DI[0].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[0].nDIVal");
	g_ConfLogic[5].DI[1].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[5].DI[1].nDTime");
	g_ConfLogic[5].DI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[1].nValue");
	g_ConfLogic[5].DI[1].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[1].nDType");
	g_ConfLogic[5].DI[1].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[1].bInvert");
	g_ConfLogic5_DI1_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic5_DI1_pSigDI_mem[0].nRemainTime");
	g_ConfLogic5_DI1_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic5_DI1_pSigDI_mem[0].nValue");
	g_ConfLogic[5].DI[1].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[1].nDIVal");
	g_ConfLogic[5].DI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[5].DI[1].nNum");
	g_ConfLogic[5].DI[1].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[5].DI[1].nUpdateTime");
	g_ConfLogic[5].DI[2].nDType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[2].nDType");
	g_ConfLogic[5].DI[2].nDTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[5].DI[2].nDTime");
	g_ConfLogic[5].DI[2].nDIVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[2].nDIVal");
	g_ConfLogic[5].DI[2].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[2].nValue");
	g_ConfLogic[5].DI[2].nUpdateTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic[5].DI[2].nUpdateTime");
	g_ConfLogic[5].DI[2].nNum = CS_INT_INPUT(int,"g_ConfLogic[5].DI[2].nNum");
	g_ConfLogic5_DI2_pSigDI_mem[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic5_DI2_pSigDI_mem[0].nValue");
	g_ConfLogic5_DI2_pSigDI_mem[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_ConfLogic5_DI2_pSigDI_mem[0].nRemainTime");
	g_ConfLogic[5].DI[2].bInvert = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DI[2].bInvert");
	g_ConfLogic[5].DO._nPulseTime = CS_UINT_INPUT(unsigned short,"g_ConfLogic[5].DO._nPulseTime");
	g_ConfLogic[5].DO.nDutyRatio = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DO.nDutyRatio");
	g_ConfLogic[5].DO.nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DO.nValue");
	g_ConfLogic[5].DO.nOutputType = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DO.nOutputType");
	g_ConfLogic[5].DO.nCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DO.nCalcVal");
	g_ConfLogic[5].DO.nActiveLevel = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DO.nActiveLevel");
	g_ConfLogic[5].DO.nPeriod = CS_UINT_INPUT(unsigned short,"g_ConfLogic[5].DO.nPeriod");
	g_ConfLogic[5].DO.nNum = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DO.nNum");
	g_ConfLogic[5].DO._DOSt = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DO._DOSt");
	g_ConfLogic[5].DO._nOldCalcVal = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].DO._nOldCalcVal");
	g_ConfLogic[5].cntOpGate = CS_INT_INPUT(int,"g_ConfLogic[5].cntOpGate");
	g_ConfLogic[5].PI[0].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].PI[0].nComp");
	g_ConfLogic[5].PI[0].nNum = CS_INT_INPUT(int,"g_ConfLogic[5].PI[0].nNum");
	g_ConfLogic5_PI0_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic5_PI0_pSigPI_mem[0].nFreqency");
	g_ConfLogic[5].PI[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[5].PI[0].nFreqency");
	g_ConfLogic[5].PI[0].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].PI[0].nSpare3[0]");
	g_ConfLogic[5].PI[0].nSpare3[1] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].PI[0].nSpare3[1]");
	g_ConfLogic[5].PI[0].nSpare3[2] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].PI[0].nSpare3[2]");
	g_ConfLogic[5].PI[0].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].PI[0].nValue");
	g_ConfLogic[5].PI[1].nComp = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].PI[1].nComp");
	g_ConfLogic5_PI1_pSigPI_mem[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic5_PI1_pSigPI_mem[0].nFreqency");
	g_ConfLogic[5].PI[1].nValue = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].PI[1].nValue");
	g_ConfLogic[5].PI[1].nFreqency = CS_UINT_INPUT(unsigned short,"g_ConfLogic[5].PI[1].nFreqency");
	g_ConfLogic[5].PI[1].nNum = CS_INT_INPUT(int,"g_ConfLogic[5].PI[1].nNum");
	g_ConfLogic[5].PI[1].nSpare3[0] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].PI[1].nSpare3[0]");
	g_ConfLogic[5].PI[1].nSpare3[1] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].PI[1].nSpare3[1]");
	g_ConfLogic[5].PI[1].nSpare3[2] = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].PI[1].nSpare3[2]");
	g_ConfLogic[5].cntPI = CS_INT_INPUT(int,"g_ConfLogic[5].cntPI");
	g_ConfLogic[5].opGate[0].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].opGate[0].Gate");
	g_ConfLogic[5].opGate[1].Gate = CS_UINT_INPUT(unsigned char,"g_ConfLogic[5].opGate[1].Gate");
	g_ConfLogic[5].cntDI = CS_INT_INPUT(int,"g_ConfLogic[5].cntDI");
	CS_STRNCPY(g_sConfBuf[0],CS_STR_INPUT(char[128],"g_sConfBuf[0]"),127);
	CS_STRNCPY(g_sConfBuf[1],CS_STR_INPUT(char[128],"g_sConfBuf[1]"),127);
	CS_STRNCPY(g_sConfBuf[2],CS_STR_INPUT(char[128],"g_sConfBuf[2]"),127);
	CS_STRNCPY(g_sConfBuf[3],CS_STR_INPUT(char[128],"g_sConfBuf[3]"),127);
	CS_STRNCPY(g_sConfBuf[4],CS_STR_INPUT(char[128],"g_sConfBuf[4]"),127);
	CS_STRNCPY(g_sConfBuf[5],CS_STR_INPUT(char[128],"g_sConfBuf[5]"),127);
	CS_STRNCPY(g_sConfData,CS_STR_INPUT(char[1024],"g_sConfData"),1023);
	g_sciTransfer_t[0].mode = CS_UINT_INPUT(unsigned int,"g_sciTransfer_t[0].mode");
	g_sciTransfer_t[0].tx_length = CS_UINT_INPUT(unsigned int,"g_sciTransfer_t[0].tx_length");
	g_sciTransfer_t[0].rx_length = CS_UINT_INPUT(unsigned int,"g_sciTransfer_t[0].rx_length");
	g_sciTransfer_t0_tx_data_mem[0] = CS_UINT_INPUT(unsigned char,"g_sciTransfer_t0_tx_data_mem[0]");
	g_sciTransfer_t0_rx_data_mem[0] = CS_UINT_INPUT(unsigned char,"g_sciTransfer_t0_rx_data_mem[0]");
	g_sigDI[0].nRemainTime = CS_UINT_INPUT(unsigned int,"g_sigDI[0].nRemainTime");
	g_sigDI[0].nValue = CS_UINT_INPUT(unsigned char,"g_sigDI[0].nValue");
	g_sigPI[0].nFreqency = CS_UINT_INPUT(unsigned short,"g_sigPI[0].nFreqency");
	i2cREG1_tmp_mem[0].DRR = CS_UINT_INPUT(unsigned char,"i2cREG1_tmp_mem[0].DRR");
	i2cREG1_tmp_mem[0].SAR = CS_UINT_INPUT(unsigned int,"i2cREG1_tmp_mem[0].SAR");
	i2cREG1_tmp_mem[0].STR = CS_UINT_INPUT(unsigned int,"i2cREG1_tmp_mem[0].STR");
	s_het1pwmPolarity[0] = CS_UINT_INPUT(unsigned int,"s_het1pwmPolarity[0]");
	s_het2pwmPolarity[0] = CS_UINT_INPUT(unsigned int,"s_het2pwmPolarity[0]");
	while_break = CS_UINT_INPUT(unsigned char,"while_break");



	/* LoadConfig() */
	LoadConfig();




	/*Output*/
	CS_INT_OUTPUT(confLogic.cntDI, "confLogic.cntDI");
	CS_INT_OUTPUT(confLogic.cntOpGate, "confLogic.cntOpGate");
	CS_INT_OUTPUT(confLogic.cntPI, "confLogic.cntPI");
	CS_UINT_OUTPUT(g_ConfLogic0_DI0_pSigDI_mem[0].nValue, "g_ConfLogic0_DI0_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic0_DI0_pSigDI_mem[0].nRemainTime, "g_ConfLogic0_DI0_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[0].nDType, "g_ConfLogic[0].DI[0].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[0].bInvert, "g_ConfLogic[0].DI[0].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[0].nDTime, "g_ConfLogic[0].DI[0].nDTime");
	CS_INT_OUTPUT(g_ConfLogic[0].DI[0].nNum, "g_ConfLogic[0].DI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[0].nUpdateTime, "g_ConfLogic[0].DI[0].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[0].nDIVal, "g_ConfLogic[0].DI[0].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[0].nValue, "g_ConfLogic[0].DI[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[1].nDTime, "g_ConfLogic[0].DI[1].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic0_DI1_pSigDI_mem[0].nRemainTime, "g_ConfLogic0_DI1_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic0_DI1_pSigDI_mem[0].nValue, "g_ConfLogic0_DI1_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[1].nDIVal, "g_ConfLogic[0].DI[1].nDIVal");
	CS_INT_OUTPUT(g_ConfLogic[0].DI[1].nNum, "g_ConfLogic[0].DI[1].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[1].nDType, "g_ConfLogic[0].DI[1].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[1].nValue, "g_ConfLogic[0].DI[1].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[1].nUpdateTime, "g_ConfLogic[0].DI[1].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[1].bInvert, "g_ConfLogic[0].DI[1].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[2].nDTime, "g_ConfLogic[0].DI[2].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[2].nDType, "g_ConfLogic[0].DI[2].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[2].nValue, "g_ConfLogic[0].DI[2].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[2].nUpdateTime, "g_ConfLogic[0].DI[2].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[2].bInvert, "g_ConfLogic[0].DI[2].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[0].DI[2].nDIVal, "g_ConfLogic[0].DI[2].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic0_DI2_pSigDI_mem[0].nValue, "g_ConfLogic0_DI2_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic0_DI2_pSigDI_mem[0].nRemainTime, "g_ConfLogic0_DI2_pSigDI_mem[0].nRemainTime");
	CS_INT_OUTPUT(g_ConfLogic[0].DI[2].nNum, "g_ConfLogic[0].DI[2].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[0].DO._nOldCalcVal, "g_ConfLogic[0].DO._nOldCalcVal");
	CS_UINT_OUTPUT(g_ConfLogic[0].DO.nActiveLevel, "g_ConfLogic[0].DO.nActiveLevel");
	CS_UINT_OUTPUT(g_ConfLogic[0].DO.nNum, "g_ConfLogic[0].DO.nNum");
	CS_UINT_OUTPUT(g_ConfLogic[0].DO._nPulseTime, "g_ConfLogic[0].DO._nPulseTime");
	CS_UINT_OUTPUT(g_ConfLogic[0].DO.nCalcVal, "g_ConfLogic[0].DO.nCalcVal");
	CS_UINT_OUTPUT(g_ConfLogic[0].DO.nValue, "g_ConfLogic[0].DO.nValue");
	CS_UINT_OUTPUT(g_ConfLogic[0].DO._DOSt, "g_ConfLogic[0].DO._DOSt");
	CS_UINT_OUTPUT(g_ConfLogic[0].DO.nPeriod, "g_ConfLogic[0].DO.nPeriod");
	CS_UINT_OUTPUT(g_ConfLogic[0].DO.nOutputType, "g_ConfLogic[0].DO.nOutputType");
	CS_UINT_OUTPUT(g_ConfLogic[0].DO.nDutyRatio, "g_ConfLogic[0].DO.nDutyRatio");
	CS_INT_OUTPUT(g_ConfLogic[0].cntOpGate, "g_ConfLogic[0].cntOpGate");
	CS_INT_OUTPUT(g_ConfLogic[0].cntPI, "g_ConfLogic[0].cntPI");
	CS_UINT_OUTPUT(g_ConfLogic[0].opGate[0].Gate, "g_ConfLogic[0].opGate[0].Gate");
	CS_UINT_OUTPUT(g_ConfLogic[0].opGate[1].Gate, "g_ConfLogic[0].opGate[1].Gate");
	CS_UINT_OUTPUT(g_ConfLogic[0].PI[0].nSpare3[0], "g_ConfLogic[0].PI[0].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic[0].PI[0].nSpare3[1], "g_ConfLogic[0].PI[0].nSpare3[1]");
	CS_UINT_OUTPUT(g_ConfLogic[0].PI[0].nSpare3[2], "g_ConfLogic[0].PI[0].nSpare3[2]");
	CS_INT_OUTPUT(g_ConfLogic[0].PI[0].nNum, "g_ConfLogic[0].PI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic0_PI0_pSigPI_mem[0].nFreqency, "g_ConfLogic0_PI0_pSigPI_mem[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[0].PI[0].nValue, "g_ConfLogic[0].PI[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[0].PI[0].nComp, "g_ConfLogic[0].PI[0].nComp");
	CS_UINT_OUTPUT(g_ConfLogic[0].PI[0].nFreqency, "g_ConfLogic[0].PI[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[0].PI[1].nSpare3[0], "g_ConfLogic[0].PI[1].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic0_PI1_pSigPI_mem[0].nFreqency, "g_ConfLogic0_PI1_pSigPI_mem[0].nFreqency");
	CS_INT_OUTPUT(g_ConfLogic[0].PI[1].nNum, "g_ConfLogic[0].PI[1].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[0].PI[1].nFreqency, "g_ConfLogic[0].PI[1].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[0].PI[1].nComp, "g_ConfLogic[0].PI[1].nComp");
	CS_UINT_OUTPUT(g_ConfLogic[0].PI[1].nValue, "g_ConfLogic[0].PI[1].nValue");
	CS_INT_OUTPUT(g_ConfLogic[0].cntDI, "g_ConfLogic[0].cntDI");
	CS_INT_OUTPUT(g_ConfLogic[1].cntDI, "g_ConfLogic[1].cntDI");
	CS_UINT_OUTPUT(g_ConfLogic[1].opGate[0].Gate, "g_ConfLogic[1].opGate[0].Gate");
	CS_UINT_OUTPUT(g_ConfLogic[1].opGate[1].Gate, "g_ConfLogic[1].opGate[1].Gate");
	CS_INT_OUTPUT(g_ConfLogic[1].cntOpGate, "g_ConfLogic[1].cntOpGate");
	CS_UINT_OUTPUT(g_ConfLogic[1].DO.nOutputType, "g_ConfLogic[1].DO.nOutputType");
	CS_UINT_OUTPUT(g_ConfLogic[1].DO.nActiveLevel, "g_ConfLogic[1].DO.nActiveLevel");
	CS_UINT_OUTPUT(g_ConfLogic[1].DO._nOldCalcVal, "g_ConfLogic[1].DO._nOldCalcVal");
	CS_UINT_OUTPUT(g_ConfLogic[1].DO._DOSt, "g_ConfLogic[1].DO._DOSt");
	CS_UINT_OUTPUT(g_ConfLogic[1].DO._nPulseTime, "g_ConfLogic[1].DO._nPulseTime");
	CS_UINT_OUTPUT(g_ConfLogic[1].DO.nPeriod, "g_ConfLogic[1].DO.nPeriod");
	CS_UINT_OUTPUT(g_ConfLogic[1].DO.nValue, "g_ConfLogic[1].DO.nValue");
	CS_UINT_OUTPUT(g_ConfLogic[1].DO.nCalcVal, "g_ConfLogic[1].DO.nCalcVal");
	CS_UINT_OUTPUT(g_ConfLogic[1].DO.nNum, "g_ConfLogic[1].DO.nNum");
	CS_UINT_OUTPUT(g_ConfLogic[1].DO.nDutyRatio, "g_ConfLogic[1].DO.nDutyRatio");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[0].nValue, "g_ConfLogic[1].PI[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[0].nComp, "g_ConfLogic[1].PI[0].nComp");
	CS_INT_OUTPUT(g_ConfLogic[1].PI[0].nNum, "g_ConfLogic[1].PI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[0].nFreqency, "g_ConfLogic[1].PI[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[0].nSpare3[0], "g_ConfLogic[1].PI[0].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[0].nSpare3[1], "g_ConfLogic[1].PI[0].nSpare3[1]");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[0].nSpare3[2], "g_ConfLogic[1].PI[0].nSpare3[2]");
	CS_UINT_OUTPUT(g_ConfLogic1_PI0_pSigPI_mem[0].nFreqency, "g_ConfLogic1_PI0_pSigPI_mem[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[1].nSpare3[0], "g_ConfLogic[1].PI[1].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[1].nSpare3[1], "g_ConfLogic[1].PI[1].nSpare3[1]");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[1].nSpare3[2], "g_ConfLogic[1].PI[1].nSpare3[2]");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[1].nValue, "g_ConfLogic[1].PI[1].nValue");
	CS_UINT_OUTPUT(g_ConfLogic1_PI1_pSigPI_mem[0].nFreqency, "g_ConfLogic1_PI1_pSigPI_mem[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[1].nComp, "g_ConfLogic[1].PI[1].nComp");
	CS_UINT_OUTPUT(g_ConfLogic[1].PI[1].nFreqency, "g_ConfLogic[1].PI[1].nFreqency");
	CS_INT_OUTPUT(g_ConfLogic[1].PI[1].nNum, "g_ConfLogic[1].PI[1].nNum");
	CS_INT_OUTPUT(g_ConfLogic[1].cntPI, "g_ConfLogic[1].cntPI");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[0].nDType, "g_ConfLogic[1].DI[0].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[0].nValue, "g_ConfLogic[1].DI[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[0].bInvert, "g_ConfLogic[1].DI[0].bInvert");
	CS_INT_OUTPUT(g_ConfLogic[1].DI[0].nNum, "g_ConfLogic[1].DI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic1_DI0_pSigDI_mem[0].nValue, "g_ConfLogic1_DI0_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic1_DI0_pSigDI_mem[0].nRemainTime, "g_ConfLogic1_DI0_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[0].nDIVal, "g_ConfLogic[1].DI[0].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[0].nUpdateTime, "g_ConfLogic[1].DI[0].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[0].nDTime, "g_ConfLogic[1].DI[0].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic1_DI1_pSigDI_mem[0].nValue, "g_ConfLogic1_DI1_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic1_DI1_pSigDI_mem[0].nRemainTime, "g_ConfLogic1_DI1_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[1].nDIVal, "g_ConfLogic[1].DI[1].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[1].bInvert, "g_ConfLogic[1].DI[1].bInvert");
	CS_INT_OUTPUT(g_ConfLogic[1].DI[1].nNum, "g_ConfLogic[1].DI[1].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[1].nDType, "g_ConfLogic[1].DI[1].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[1].nDTime, "g_ConfLogic[1].DI[1].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[1].nUpdateTime, "g_ConfLogic[1].DI[1].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[1].nValue, "g_ConfLogic[1].DI[1].nValue");
	CS_UINT_OUTPUT(g_ConfLogic1_DI2_pSigDI_mem[0].nRemainTime, "g_ConfLogic1_DI2_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic1_DI2_pSigDI_mem[0].nValue, "g_ConfLogic1_DI2_pSigDI_mem[0].nValue");
	CS_INT_OUTPUT(g_ConfLogic[1].DI[2].nNum, "g_ConfLogic[1].DI[2].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[2].nDIVal, "g_ConfLogic[1].DI[2].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[2].nUpdateTime, "g_ConfLogic[1].DI[2].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[2].nValue, "g_ConfLogic[1].DI[2].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[2].nDTime, "g_ConfLogic[1].DI[2].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[2].bInvert, "g_ConfLogic[1].DI[2].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[1].DI[2].nDType, "g_ConfLogic[1].DI[2].nDType");
	CS_INT_OUTPUT(g_ConfLogic[2].cntPI, "g_ConfLogic[2].cntPI");
	CS_INT_OUTPUT(g_ConfLogic[2].cntOpGate, "g_ConfLogic[2].cntOpGate");
	CS_UINT_OUTPUT(g_ConfLogic[2].DO.nPeriod, "g_ConfLogic[2].DO.nPeriod");
	CS_UINT_OUTPUT(g_ConfLogic[2].DO._DOSt, "g_ConfLogic[2].DO._DOSt");
	CS_UINT_OUTPUT(g_ConfLogic[2].DO.nValue, "g_ConfLogic[2].DO.nValue");
	CS_UINT_OUTPUT(g_ConfLogic[2].DO.nNum, "g_ConfLogic[2].DO.nNum");
	CS_UINT_OUTPUT(g_ConfLogic[2].DO.nCalcVal, "g_ConfLogic[2].DO.nCalcVal");
	CS_UINT_OUTPUT(g_ConfLogic[2].DO.nOutputType, "g_ConfLogic[2].DO.nOutputType");
	CS_UINT_OUTPUT(g_ConfLogic[2].DO._nOldCalcVal, "g_ConfLogic[2].DO._nOldCalcVal");
	CS_UINT_OUTPUT(g_ConfLogic[2].DO.nActiveLevel, "g_ConfLogic[2].DO.nActiveLevel");
	CS_UINT_OUTPUT(g_ConfLogic[2].DO.nDutyRatio, "g_ConfLogic[2].DO.nDutyRatio");
	CS_UINT_OUTPUT(g_ConfLogic[2].DO._nPulseTime, "g_ConfLogic[2].DO._nPulseTime");
	CS_UINT_OUTPUT(g_ConfLogic2_PI0_pSigPI_mem[0].nFreqency, "g_ConfLogic2_PI0_pSigPI_mem[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[0].nComp, "g_ConfLogic[2].PI[0].nComp");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[0].nSpare3[0], "g_ConfLogic[2].PI[0].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[0].nSpare3[1], "g_ConfLogic[2].PI[0].nSpare3[1]");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[0].nSpare3[2], "g_ConfLogic[2].PI[0].nSpare3[2]");
	CS_INT_OUTPUT(g_ConfLogic[2].PI[0].nNum, "g_ConfLogic[2].PI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[0].nFreqency, "g_ConfLogic[2].PI[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[0].nValue, "g_ConfLogic[2].PI[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[1].nValue, "g_ConfLogic[2].PI[1].nValue");
	CS_UINT_OUTPUT(g_ConfLogic2_PI1_pSigPI_mem[0].nFreqency, "g_ConfLogic2_PI1_pSigPI_mem[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[1].nFreqency, "g_ConfLogic[2].PI[1].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[1].nComp, "g_ConfLogic[2].PI[1].nComp");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[1].nSpare3[0], "g_ConfLogic[2].PI[1].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[1].nSpare3[1], "g_ConfLogic[2].PI[1].nSpare3[1]");
	CS_UINT_OUTPUT(g_ConfLogic[2].PI[1].nSpare3[2], "g_ConfLogic[2].PI[1].nSpare3[2]");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[0].nUpdateTime, "g_ConfLogic[2].DI[0].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[0].nDTime, "g_ConfLogic[2].DI[0].nDTime");
	CS_INT_OUTPUT(g_ConfLogic[2].DI[0].nNum, "g_ConfLogic[2].DI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[0].nValue, "g_ConfLogic[2].DI[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[0].bInvert, "g_ConfLogic[2].DI[0].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic2_DI0_pSigDI_mem[0].nRemainTime, "g_ConfLogic2_DI0_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic2_DI0_pSigDI_mem[0].nValue, "g_ConfLogic2_DI0_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[0].nDIVal, "g_ConfLogic[2].DI[0].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[0].nDType, "g_ConfLogic[2].DI[0].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[1].nUpdateTime, "g_ConfLogic[2].DI[1].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[1].nDTime, "g_ConfLogic[2].DI[1].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[1].bInvert, "g_ConfLogic[2].DI[1].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[1].nValue, "g_ConfLogic[2].DI[1].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[1].nDType, "g_ConfLogic[2].DI[1].nDType");
	CS_UINT_OUTPUT(g_ConfLogic2_DI1_pSigDI_mem[0].nValue, "g_ConfLogic2_DI1_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic2_DI1_pSigDI_mem[0].nRemainTime, "g_ConfLogic2_DI1_pSigDI_mem[0].nRemainTime");
	CS_INT_OUTPUT(g_ConfLogic[2].DI[1].nNum, "g_ConfLogic[2].DI[1].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[1].nDIVal, "g_ConfLogic[2].DI[1].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[2].nDType, "g_ConfLogic[2].DI[2].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[2].nDIVal, "g_ConfLogic[2].DI[2].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[2].nValue, "g_ConfLogic[2].DI[2].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[2].bInvert, "g_ConfLogic[2].DI[2].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[2].nDTime, "g_ConfLogic[2].DI[2].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[2].DI[2].nUpdateTime, "g_ConfLogic[2].DI[2].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic2_DI2_pSigDI_mem[0].nValue, "g_ConfLogic2_DI2_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic2_DI2_pSigDI_mem[0].nRemainTime, "g_ConfLogic2_DI2_pSigDI_mem[0].nRemainTime");
	CS_INT_OUTPUT(g_ConfLogic[2].DI[2].nNum, "g_ConfLogic[2].DI[2].nNum");
	CS_INT_OUTPUT(g_ConfLogic[2].cntDI, "g_ConfLogic[2].cntDI");
	CS_UINT_OUTPUT(g_ConfLogic[2].opGate[0].Gate, "g_ConfLogic[2].opGate[0].Gate");
	CS_UINT_OUTPUT(g_ConfLogic[2].opGate[1].Gate, "g_ConfLogic[2].opGate[1].Gate");
	CS_INT_OUTPUT(g_ConfLogic[3].cntPI, "g_ConfLogic[3].cntPI");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[0].nFreqency, "g_ConfLogic[3].PI[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[0].nComp, "g_ConfLogic[3].PI[0].nComp");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[0].nSpare3[0], "g_ConfLogic[3].PI[0].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[0].nSpare3[1], "g_ConfLogic[3].PI[0].nSpare3[1]");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[0].nSpare3[2], "g_ConfLogic[3].PI[0].nSpare3[2]");
	CS_INT_OUTPUT(g_ConfLogic[3].PI[0].nNum, "g_ConfLogic[3].PI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic3_PI0_pSigPI_mem[0].nFreqency, "g_ConfLogic3_PI0_pSigPI_mem[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[0].nValue, "g_ConfLogic[3].PI[0].nValue");
	CS_INT_OUTPUT(g_ConfLogic[3].PI[1].nNum, "g_ConfLogic[3].PI[1].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[1].nFreqency, "g_ConfLogic[3].PI[1].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[1].nComp, "g_ConfLogic[3].PI[1].nComp");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[1].nValue, "g_ConfLogic[3].PI[1].nValue");
	CS_UINT_OUTPUT(g_ConfLogic3_PI1_pSigPI_mem[0].nFreqency, "g_ConfLogic3_PI1_pSigPI_mem[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[1].nSpare3[0], "g_ConfLogic[3].PI[1].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[1].nSpare3[1], "g_ConfLogic[3].PI[1].nSpare3[1]");
	CS_UINT_OUTPUT(g_ConfLogic[3].PI[1].nSpare3[2], "g_ConfLogic[3].PI[1].nSpare3[2]");
	CS_UINT_OUTPUT(g_ConfLogic[3].opGate[0].Gate, "g_ConfLogic[3].opGate[0].Gate");
	CS_UINT_OUTPUT(g_ConfLogic[3].opGate[1].Gate, "g_ConfLogic[3].opGate[1].Gate");
	CS_UINT_OUTPUT(g_ConfLogic[3].DO._nPulseTime, "g_ConfLogic[3].DO._nPulseTime");
	CS_UINT_OUTPUT(g_ConfLogic[3].DO._DOSt, "g_ConfLogic[3].DO._DOSt");
	CS_UINT_OUTPUT(g_ConfLogic[3].DO.nActiveLevel, "g_ConfLogic[3].DO.nActiveLevel");
	CS_UINT_OUTPUT(g_ConfLogic[3].DO.nDutyRatio, "g_ConfLogic[3].DO.nDutyRatio");
	CS_UINT_OUTPUT(g_ConfLogic[3].DO._nOldCalcVal, "g_ConfLogic[3].DO._nOldCalcVal");
	CS_UINT_OUTPUT(g_ConfLogic[3].DO.nValue, "g_ConfLogic[3].DO.nValue");
	CS_UINT_OUTPUT(g_ConfLogic[3].DO.nOutputType, "g_ConfLogic[3].DO.nOutputType");
	CS_UINT_OUTPUT(g_ConfLogic[3].DO.nPeriod, "g_ConfLogic[3].DO.nPeriod");
	CS_UINT_OUTPUT(g_ConfLogic[3].DO.nNum, "g_ConfLogic[3].DO.nNum");
	CS_UINT_OUTPUT(g_ConfLogic[3].DO.nCalcVal, "g_ConfLogic[3].DO.nCalcVal");
	CS_INT_OUTPUT(g_ConfLogic[3].cntOpGate, "g_ConfLogic[3].cntOpGate");
	CS_INT_OUTPUT(g_ConfLogic[3].cntDI, "g_ConfLogic[3].cntDI");
	CS_UINT_OUTPUT(g_ConfLogic3_DI0_pSigDI_mem[0].nValue, "g_ConfLogic3_DI0_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic3_DI0_pSigDI_mem[0].nRemainTime, "g_ConfLogic3_DI0_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[0].nDIVal, "g_ConfLogic[3].DI[0].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[0].nDTime, "g_ConfLogic[3].DI[0].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[0].bInvert, "g_ConfLogic[3].DI[0].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[0].nValue, "g_ConfLogic[3].DI[0].nValue");
	CS_INT_OUTPUT(g_ConfLogic[3].DI[0].nNum, "g_ConfLogic[3].DI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[0].nUpdateTime, "g_ConfLogic[3].DI[0].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[0].nDType, "g_ConfLogic[3].DI[0].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[1].nUpdateTime, "g_ConfLogic[3].DI[1].nUpdateTime");
	CS_INT_OUTPUT(g_ConfLogic[3].DI[1].nNum, "g_ConfLogic[3].DI[1].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[1].nValue, "g_ConfLogic[3].DI[1].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[1].nDType, "g_ConfLogic[3].DI[1].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[1].nDIVal, "g_ConfLogic[3].DI[1].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[1].bInvert, "g_ConfLogic[3].DI[1].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[1].nDTime, "g_ConfLogic[3].DI[1].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic3_DI1_pSigDI_mem[0].nRemainTime, "g_ConfLogic3_DI1_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic3_DI1_pSigDI_mem[0].nValue, "g_ConfLogic3_DI1_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[2].nUpdateTime, "g_ConfLogic[3].DI[2].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[2].bInvert, "g_ConfLogic[3].DI[2].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[2].nDTime, "g_ConfLogic[3].DI[2].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[2].nDType, "g_ConfLogic[3].DI[2].nDType");
	CS_UINT_OUTPUT(g_ConfLogic3_DI2_pSigDI_mem[0].nRemainTime, "g_ConfLogic3_DI2_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic3_DI2_pSigDI_mem[0].nValue, "g_ConfLogic3_DI2_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[2].nDIVal, "g_ConfLogic[3].DI[2].nDIVal");
	CS_INT_OUTPUT(g_ConfLogic[3].DI[2].nNum, "g_ConfLogic[3].DI[2].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[3].DI[2].nValue, "g_ConfLogic[3].DI[2].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[4].DO.nActiveLevel, "g_ConfLogic[4].DO.nActiveLevel");
	CS_UINT_OUTPUT(g_ConfLogic[4].DO.nNum, "g_ConfLogic[4].DO.nNum");
	CS_UINT_OUTPUT(g_ConfLogic[4].DO._nPulseTime, "g_ConfLogic[4].DO._nPulseTime");
	CS_UINT_OUTPUT(g_ConfLogic[4].DO.nDutyRatio, "g_ConfLogic[4].DO.nDutyRatio");
	CS_UINT_OUTPUT(g_ConfLogic[4].DO.nCalcVal, "g_ConfLogic[4].DO.nCalcVal");
	CS_UINT_OUTPUT(g_ConfLogic[4].DO.nValue, "g_ConfLogic[4].DO.nValue");
	CS_UINT_OUTPUT(g_ConfLogic[4].DO.nOutputType, "g_ConfLogic[4].DO.nOutputType");
	CS_UINT_OUTPUT(g_ConfLogic[4].DO._DOSt, "g_ConfLogic[4].DO._DOSt");
	CS_UINT_OUTPUT(g_ConfLogic[4].DO.nPeriod, "g_ConfLogic[4].DO.nPeriod");
	CS_UINT_OUTPUT(g_ConfLogic[4].DO._nOldCalcVal, "g_ConfLogic[4].DO._nOldCalcVal");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[0].nComp, "g_ConfLogic[4].PI[0].nComp");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[0].nValue, "g_ConfLogic[4].PI[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[0].nFreqency, "g_ConfLogic[4].PI[0].nFreqency");
	CS_INT_OUTPUT(g_ConfLogic[4].PI[0].nNum, "g_ConfLogic[4].PI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic4_PI0_pSigPI_mem[0].nFreqency, "g_ConfLogic4_PI0_pSigPI_mem[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[0].nSpare3[0], "g_ConfLogic[4].PI[0].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[0].nSpare3[1], "g_ConfLogic[4].PI[0].nSpare3[1]");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[0].nSpare3[2], "g_ConfLogic[4].PI[0].nSpare3[2]");
	CS_INT_OUTPUT(g_ConfLogic[4].PI[1].nNum, "g_ConfLogic[4].PI[1].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[1].nFreqency, "g_ConfLogic[4].PI[1].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic4_PI1_pSigPI_mem[0].nFreqency, "g_ConfLogic4_PI1_pSigPI_mem[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[1].nValue, "g_ConfLogic[4].PI[1].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[1].nComp, "g_ConfLogic[4].PI[1].nComp");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[1].nSpare3[0], "g_ConfLogic[4].PI[1].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[1].nSpare3[1], "g_ConfLogic[4].PI[1].nSpare3[1]");
	CS_UINT_OUTPUT(g_ConfLogic[4].PI[1].nSpare3[2], "g_ConfLogic[4].PI[1].nSpare3[2]");
	CS_INT_OUTPUT(g_ConfLogic[4].cntPI, "g_ConfLogic[4].cntPI");
	CS_INT_OUTPUT(g_ConfLogic[4].cntOpGate, "g_ConfLogic[4].cntOpGate");
	CS_UINT_OUTPUT(g_ConfLogic[4].opGate[0].Gate, "g_ConfLogic[4].opGate[0].Gate");
	CS_UINT_OUTPUT(g_ConfLogic[4].opGate[1].Gate, "g_ConfLogic[4].opGate[1].Gate");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[0].nDType, "g_ConfLogic[4].DI[0].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[0].nValue, "g_ConfLogic[4].DI[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[0].nDTime, "g_ConfLogic[4].DI[0].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[0].bInvert, "g_ConfLogic[4].DI[0].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic4_DI0_pSigDI_mem[0].nValue, "g_ConfLogic4_DI0_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic4_DI0_pSigDI_mem[0].nRemainTime, "g_ConfLogic4_DI0_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[0].nDIVal, "g_ConfLogic[4].DI[0].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[0].nUpdateTime, "g_ConfLogic[4].DI[0].nUpdateTime");
	CS_INT_OUTPUT(g_ConfLogic[4].DI[0].nNum, "g_ConfLogic[4].DI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic4_DI1_pSigDI_mem[0].nValue, "g_ConfLogic4_DI1_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic4_DI1_pSigDI_mem[0].nRemainTime, "g_ConfLogic4_DI1_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[1].nValue, "g_ConfLogic[4].DI[1].nValue");
	CS_INT_OUTPUT(g_ConfLogic[4].DI[1].nNum, "g_ConfLogic[4].DI[1].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[1].nDIVal, "g_ConfLogic[4].DI[1].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[1].bInvert, "g_ConfLogic[4].DI[1].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[1].nDTime, "g_ConfLogic[4].DI[1].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[1].nUpdateTime, "g_ConfLogic[4].DI[1].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[1].nDType, "g_ConfLogic[4].DI[1].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[2].nUpdateTime, "g_ConfLogic[4].DI[2].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[2].nDType, "g_ConfLogic[4].DI[2].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[2].nValue, "g_ConfLogic[4].DI[2].nValue");
	CS_UINT_OUTPUT(g_ConfLogic4_DI2_pSigDI_mem[0].nValue, "g_ConfLogic4_DI2_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic4_DI2_pSigDI_mem[0].nRemainTime, "g_ConfLogic4_DI2_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[2].nDIVal, "g_ConfLogic[4].DI[2].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[2].bInvert, "g_ConfLogic[4].DI[2].bInvert");
	CS_INT_OUTPUT(g_ConfLogic[4].DI[2].nNum, "g_ConfLogic[4].DI[2].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[4].DI[2].nDTime, "g_ConfLogic[4].DI[2].nDTime");
	CS_INT_OUTPUT(g_ConfLogic[4].cntDI, "g_ConfLogic[4].cntDI");
	CS_INT_OUTPUT(g_ConfLogic[5].DI[0].nNum, "g_ConfLogic[5].DI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[0].bInvert, "g_ConfLogic[5].DI[0].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[0].nDType, "g_ConfLogic[5].DI[0].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[0].nUpdateTime, "g_ConfLogic[5].DI[0].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic5_DI0_pSigDI_mem[0].nValue, "g_ConfLogic5_DI0_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic5_DI0_pSigDI_mem[0].nRemainTime, "g_ConfLogic5_DI0_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[0].nValue, "g_ConfLogic[5].DI[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[0].nDTime, "g_ConfLogic[5].DI[0].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[0].nDIVal, "g_ConfLogic[5].DI[0].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[1].nDTime, "g_ConfLogic[5].DI[1].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[1].nValue, "g_ConfLogic[5].DI[1].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[1].nDType, "g_ConfLogic[5].DI[1].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[1].bInvert, "g_ConfLogic[5].DI[1].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic5_DI1_pSigDI_mem[0].nRemainTime, "g_ConfLogic5_DI1_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic5_DI1_pSigDI_mem[0].nValue, "g_ConfLogic5_DI1_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[1].nDIVal, "g_ConfLogic[5].DI[1].nDIVal");
	CS_INT_OUTPUT(g_ConfLogic[5].DI[1].nNum, "g_ConfLogic[5].DI[1].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[1].nUpdateTime, "g_ConfLogic[5].DI[1].nUpdateTime");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[2].nDType, "g_ConfLogic[5].DI[2].nDType");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[2].nDTime, "g_ConfLogic[5].DI[2].nDTime");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[2].nDIVal, "g_ConfLogic[5].DI[2].nDIVal");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[2].nValue, "g_ConfLogic[5].DI[2].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[2].nUpdateTime, "g_ConfLogic[5].DI[2].nUpdateTime");
	CS_INT_OUTPUT(g_ConfLogic[5].DI[2].nNum, "g_ConfLogic[5].DI[2].nNum");
	CS_UINT_OUTPUT(g_ConfLogic5_DI2_pSigDI_mem[0].nValue, "g_ConfLogic5_DI2_pSigDI_mem[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic5_DI2_pSigDI_mem[0].nRemainTime, "g_ConfLogic5_DI2_pSigDI_mem[0].nRemainTime");
	CS_UINT_OUTPUT(g_ConfLogic[5].DI[2].bInvert, "g_ConfLogic[5].DI[2].bInvert");
	CS_UINT_OUTPUT(g_ConfLogic[5].DO._nPulseTime, "g_ConfLogic[5].DO._nPulseTime");
	CS_UINT_OUTPUT(g_ConfLogic[5].DO.nDutyRatio, "g_ConfLogic[5].DO.nDutyRatio");
	CS_UINT_OUTPUT(g_ConfLogic[5].DO.nValue, "g_ConfLogic[5].DO.nValue");
	CS_UINT_OUTPUT(g_ConfLogic[5].DO.nOutputType, "g_ConfLogic[5].DO.nOutputType");
	CS_UINT_OUTPUT(g_ConfLogic[5].DO.nCalcVal, "g_ConfLogic[5].DO.nCalcVal");
	CS_UINT_OUTPUT(g_ConfLogic[5].DO.nActiveLevel, "g_ConfLogic[5].DO.nActiveLevel");
	CS_UINT_OUTPUT(g_ConfLogic[5].DO.nPeriod, "g_ConfLogic[5].DO.nPeriod");
	CS_UINT_OUTPUT(g_ConfLogic[5].DO.nNum, "g_ConfLogic[5].DO.nNum");
	CS_UINT_OUTPUT(g_ConfLogic[5].DO._DOSt, "g_ConfLogic[5].DO._DOSt");
	CS_UINT_OUTPUT(g_ConfLogic[5].DO._nOldCalcVal, "g_ConfLogic[5].DO._nOldCalcVal");
	CS_INT_OUTPUT(g_ConfLogic[5].cntOpGate, "g_ConfLogic[5].cntOpGate");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[0].nComp, "g_ConfLogic[5].PI[0].nComp");
	CS_INT_OUTPUT(g_ConfLogic[5].PI[0].nNum, "g_ConfLogic[5].PI[0].nNum");
	CS_UINT_OUTPUT(g_ConfLogic5_PI0_pSigPI_mem[0].nFreqency, "g_ConfLogic5_PI0_pSigPI_mem[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[0].nFreqency, "g_ConfLogic[5].PI[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[0].nSpare3[0], "g_ConfLogic[5].PI[0].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[0].nSpare3[1], "g_ConfLogic[5].PI[0].nSpare3[1]");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[0].nSpare3[2], "g_ConfLogic[5].PI[0].nSpare3[2]");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[0].nValue, "g_ConfLogic[5].PI[0].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[1].nComp, "g_ConfLogic[5].PI[1].nComp");
	CS_UINT_OUTPUT(g_ConfLogic5_PI1_pSigPI_mem[0].nFreqency, "g_ConfLogic5_PI1_pSigPI_mem[0].nFreqency");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[1].nValue, "g_ConfLogic[5].PI[1].nValue");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[1].nFreqency, "g_ConfLogic[5].PI[1].nFreqency");
	CS_INT_OUTPUT(g_ConfLogic[5].PI[1].nNum, "g_ConfLogic[5].PI[1].nNum");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[1].nSpare3[0], "g_ConfLogic[5].PI[1].nSpare3[0]");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[1].nSpare3[1], "g_ConfLogic[5].PI[1].nSpare3[1]");
	CS_UINT_OUTPUT(g_ConfLogic[5].PI[1].nSpare3[2], "g_ConfLogic[5].PI[1].nSpare3[2]");
	CS_INT_OUTPUT(g_ConfLogic[5].cntPI, "g_ConfLogic[5].cntPI");
	CS_UINT_OUTPUT(g_ConfLogic[5].opGate[0].Gate, "g_ConfLogic[5].opGate[0].Gate");
	CS_UINT_OUTPUT(g_ConfLogic[5].opGate[1].Gate, "g_ConfLogic[5].opGate[1].Gate");
	CS_INT_OUTPUT(g_ConfLogic[5].cntDI, "g_ConfLogic[5].cntDI");
	CS_UINT_OUTPUT(g_sciTransfer_t[0].mode, "g_sciTransfer_t[0].mode");
	CS_UINT_OUTPUT(g_sciTransfer_t[0].tx_length, "g_sciTransfer_t[0].tx_length");
	CS_UINT_OUTPUT(g_sciTransfer_t[0].rx_length, "g_sciTransfer_t[0].rx_length");
	CS_UINT_OUTPUT(i2cREG1_tmp_mem[0].DRR, "i2cREG1_tmp_mem[0].DRR");
	CS_UINT_OUTPUT(i2cREG1_tmp_mem[0].SAR, "i2cREG1_tmp_mem[0].SAR");
	CS_UINT_OUTPUT(i2cREG1_tmp_mem[0].STR, "i2cREG1_tmp_mem[0].STR");
	CS_UINT_OUTPUT(s_het1pwmPolarity[0], "s_het1pwmPolarity[0]");
	CS_UINT_OUTPUT(s_het2pwmPolarity[0], "s_het2pwmPolarity[0]");

	/*<END TEST>*/}
	/*<CS_DISCONNECT_CODE_START>*/
	/*Do not remove disConnect_stub_configuration()*/
	disConnect_LoadConfig_test0_stub_configuration();
	/*<CS_DISCONNECT_CODE_END>*/
}

#endif
